<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNumberUser()
    {
        $q = $this->createQueryBuilder('u')
            ->select('COUNT(u.id) as nbUsers')
            ->where('u.active = 1')
            ->andWhere('u.enable = 1');

        return $q->getQuery()->getOneOrNullResult();
    }
}
