security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        user_provider:
            entity:
                class: AppBundle:User
                property: username

    role_hierarchy:
            ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        main:
            pattern:    ^/
            http_basic: ~
            provider: user_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /welcome

    access_control:
            - { path: ^/admin, roles: ROLE_ADMIN }
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/registration/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/welcome, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/, roles: IS_AUTHENTICATED_FULLY  }
