# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    wikipedia_functions:
        class: AppBundle\Services\WikipediaFunctions

    youtube_functions:
            class: AppBundle\Services\YoutubeFunctions

    deezer_functions:
            class: AppBundle\Services\DeezerFunctions

    spotify_functions:
            class: AppBundle\Services\SpotifyFunctions

    soundcloud_functions:
            class: AppBundle\Services\SoundcloudFunctions