# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
  # app.google.oauth: googleoauth

services:
    wikipedia_functions:
        class: AppBundle\Services\WikipediaFunctions

    youtube_functions:
            class: AppBundle\Services\YoutubeFunctions
            
            arguments: ['%youtube_client_id%', '%youtube_client_secret%', '%youtube_api_key%']


    deezer_functions:
            class: AppBundle\Services\DeezerFunctions

            arguments: ['%deezer_client_id%', '%deezer_client_secret%', 'deezer_callback', '@router']


    spotify_functions:
            class: AppBundle\Services\SpotifyFunctions

            arguments: ['%spotify_client_id%', '%spotify_client_secret%', 'spotify_callback', '@router']


    soundcloud_functions:
            class: AppBundle\Services\SoundcloudFunctions
