parameters:

services:
    lastfm_functions:
        class: AppBundle\Services\LastFMFunctions
        arguments: ['%lastfm_api_key%']

    youtube_functions:
            class: AppBundle\Services\YoutubeFunctions
            arguments: ['%youtube_client_id%', '%youtube_client_secret%', '%youtube_api_key%']


    deezer_functions:
            class: AppBundle\Services\DeezerFunctions

    spotify_functions:
            class: AppBundle\Services\SpotifyFunctions

    soundcloud_functions:
            class: AppBundle\Services\SoundcloudFunctions
